# Generated by Django 4.1.7 on 2023-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Original URL')),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Short URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='How many times hit')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
            ],
        ),
    ]
